spring.application.name=MoniveaBC_OOP_Project
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:file:./data/MemberDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=ADMIN
spring.datasource.password=securepassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

rollcall.service.url=http://localhost:8081

